name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  
jobs:
  deploy-docker-hello-world:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/thedatabaseme/hello-world
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - name: Deploy in EC2
        uses: appleboy/ssh-action@v0.1.10
        env:
          PATH_REPO: "/data/repo/vingroupventure.cc"
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          debug: false
          envs: PATH_REPO
          script: |
            cd $PATH_REPO
            git checkout ${{ github.head_ref || github.ref_name }}
            git fetch --all
            git reset --hard origin/${{ github.head_ref || github.ref_name }}
            git pull origin ${{ github.head_ref || github.ref_name }}
            npm install --force
            pm2 start ecosystem.config.js -i 1