name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  PATH_COMPOSER: /tmp/vingroupventure.cc

jobs:
  build-push:
    environment: production
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: mr-smithers-excellent/docker-build-push@v6
        id: build-push-action
        name: Build & push Docker image
        with:
          image: ${{ github.event.repository.name }}
          addLatest: false
          addTimestamp: false
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
    outputs:
      image_full_name: ${{ steps.build-push-action.outputs.imageFullName }}
  pull:
    environment: production
    runs-on: self-hosted
    needs: build-push
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Pull and run
        uses: appleboy/ssh-action@v0.1.10
        env:
          PATH_REPO: "/data/repo/vingroupventure.cc"
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          debug: false
          envs: PATH_REPO
          script: |
            cd $PATH_REPO
            git checkout ${{ github.head_ref || github.ref_name }}
            git fetch --all
            git reset --hard origin/${{ github.head_ref || github.ref_name }}
            git pull origin ${{ github.head_ref || github.ref_name }}
            cp docker-compose/docker-compose-prod.yml ${{ env.PATH_COMPOSER }}/docker-compose.yml
            sed -i "s~IMAGE_TAG~${{ needs.build-push-action.outputs.image_full_name }}~g" ${{ env.PATH_COMPOSER }}/docker-compose.yml
            echo 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 | docker login ghcr.io -u dangvanduc90 --password-stdin
            cd ${{ env.PATH_COMPOSER }} && docker compose up -d